# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  latest: 'latest'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.15.0'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
     command: 'install'
  displayName: 'npm install'

- script: |
    npm run test
  displayName: 'npm test'

- task: Docker@2
  displayName: Build and push image
  inputs:
    containerRegistry: 'Docker hub'
    repository: 'sagudeloo/movie-analyst-ui'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '$(latest)'
